version: "3"
services:

  nginx:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"