# Generated by Django 4.2 on 2023-05-01 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='carwashservice',
            old_name='service_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='carwashservice',
            name='service_description',
        ),
        migrations.AddField(
            model_name='carwashservice',
            name='description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AddField(
            model_name='carwashservice',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.servicetype'),
        ),
    ]
