# Generated by Django 4.2 on 2023-05-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_servicetype_rename_service_date_carwashservice_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarWashService',
            new_name='Service',
        ),
    ]
