# Generated by Django 4.2 on 2023-05-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_carwashservice_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceType',
            new_name='Type',
        ),
    ]
